### ISSUE TITLE
xs-dev setup permissions issue

### ISSUE THREAD

**Issue by waldopt** [HipsterBrown/xs-dev#110]
I am setting up a dedicated OSX laptop for Moddable/xs-dev development and running into an issue following the documentation.

After preparing the laptop with the requirements when I run the xs-dev setup command I get a permissions error running the script. 
permission denied, mkdir '/usr/local/lib/node_modules/xs-dev'

I have a freshly formatted MacBook Pro with Ventura 13.2.1 installed. Xcode and its CLI tools installed. I have only one account on this laptop and I am the Administrator.
I installed Node.js (followed the link in xs-dev/introduction and installed from the node.js OSX installer) I can confirm in terminal that node v18.15.0 and rpm 9.5.0 are installed. I can see that /usr/local/bin is in my $PATH.
I have installed Homebrew.

When running the xs-dev setup command I get:
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/xs-dev
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/xs-dev'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/xs-dev'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/xs-dev'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

I am assuming that because I installed node.js as an administrator permissions should not be an issue. 
Advice would be appreciated, thanks

**Comment by HipsterBrown** [comment]
This sounds like a known issue with npm and global dependencies: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally


Do either of the options described here help resolve the issue? https://stackoverflow.com/a/65761457

**Comment by waldopt** [comment]
Thank you for the permissions advice. Using the advice in the stackoverflow post I am able to fix the node.js install permissions and run the **npm install -g xs-dev** command. Unfortunately I am still having an issue running XS-dev to build a sample app. I get a message I need to have Moddable tooling. When I do that it appears to run successfully but the no tooling message still shows. I am using bash and the profile file is empty. Thank you for your help on this.
<img width="1425" alt="Screenshot 2023-03-11 at 9 28 59 AM" src="https://user-images.githubusercontent.com/7000186/224503133-d5bbe968-8ccc-4548-98ea-c8c7a24a7a62.png">

**Comment by phoddie** [comment]
@waldopt, if you do `echo $MODDABLE` in that new terminal window, what does it show?

**Comment by waldopt** [comment]
<img width="581" alt="Screenshot 2023-03-11 at 9 57 21 AM" src="https://user-images.githubusercontent.com/7000186/224504291-a73c8bd5-725f-4c19-98e7-d33540ca10b9.png">

**Comment by phoddie** [comment]
Thanks. That explains why it can't find the tooling. I defer to @HipsterBrown on why the shell start-up script isn't getting updated here.

**Comment by HipsterBrown** [comment]
@waldopt if you run `source ~/.local/share/xs-dev-export.sh`? Does that give you the `$MODDABLE` environment variable?

That source command should be in your `~/.zshrc` since it looks like you're using the stock zsh shell provided by MacOS.

**Comment by HipsterBrown** [comment]
Oh I just looked a bit closer at the screenshot. It appears the terminal is using bash instead of zsh. What does `echo $SHELL` return? 

This is good feedback for a troubleshooting section of the docs.

**Comment by waldopt** [comment]
<img width="586" alt="Screenshot 2023-03-11 at 10 49 30 AM" src="https://user-images.githubusercontent.com/7000186/224506343-761055f2-2574-49e9-a6e4-a992109d094f.png">

**Comment by waldopt** [comment]
This is looking at the file contents. Seems like for some reason it is not getting populated
<img width="1169" alt="Screenshot 2023-03-11 at 11 39 31 AM" src="https://user-images.githubusercontent.com/7000186/224508381-cbbbb482-7349-4a9d-abce-a7bb31c4aa55.png">

**Comment by HipsterBrown** [comment]
So if the shell is detected as bash or zsh, the `bashrc` or `zshrc` file is used to set up the shell session tooling and environment variables. Can you check either of those?

**Comment by waldopt** [comment]
Both of those look empty at this point. 
<img width="1365" alt="Screenshot 2023-03-11 at 2 05 45 PM" src="https://user-images.githubusercontent.com/7000186/224513491-2c8a1b36-a83b-467b-a66e-9a998b5313cf.png">

**Comment by waldopt** [comment]
I ran xs-dev setup again and checked and both files are still empty. This is a fresh OSX system install so nothing else has been installed on this machine. Not sure that should affect anything but sharing in case important.

**Comment by HipsterBrown** [comment]
Thanks for the additional context about the fresh install. I guess the last place to look for the shell setup code is the `~/.profile` file. I'll look into adding some more feedback in the setup command. 

What does `xs-dev info` display?

**Comment by waldopt** [comment]
Maybe something here...
<img width="1341" alt="Screenshot 2023-03-11 at 3 04 12 PM" src="https://user-images.githubusercontent.com/7000186/224515301-b4371b1b-010f-4fe7-91d9-dc152dbfb368.png">

**Comment by HipsterBrown** [comment]
Eureka! If you copy that file or rename it to `.bashrc` or `.zshrc`, I wonder if that will resolve the issue for now.

**Comment by waldopt** [comment]
I added that line to both .bashrc and .zshrc. But still getting the tooling error. 
<img width="1204" alt="Screenshot 2023-03-11 at 3 21 23 PM" src="https://user-images.githubusercontent.com/7000186/224515871-ca975605-eafb-45c9-8abb-8701ae2dd909.png">

**Comment by phoddie** [comment]
@HipsterBrown – regarding the problem where the `source` command isn't making it into the shell start-up script, I had a question. Since xs-dev already detects that because $MODDABLE is undefined could xs-dev fix that by sourcing `~/.local/share/xs-dev-export.sh`? This would have a couple of benefits -- it would fix one of the problems @waldopt encountered and it would eliminate the need to start a terminal window after certain steps (I've made the mistake of forgetting to do that more than once...).

I did something similar a couple months back for the ESP-IDF builds where it will source the IDF exports automatically if they aren't found. That solved some problems developers were bumping into.

I suppose you might want to create an environment variable for xs-dev to use for the check, rather than $MODDABLE. That would eliminate potential ambiguities such as a developer having defined $MODDABLE themselves being mistaken for xs-dev-export.sh having been run.

All that said, I am a **rookie** shell programmer. Feel free to tell me if it is a bad idea. ;)

**Comment by HipsterBrown** [comment]
The potential fix has been released with v0.24.0 of xs-dev: https://github.com/HipsterBrown/xs-dev/releases/tag/v0.24.0

@waldopt Please feel free to re-open this issue if this new release does not resolve it.

**Comment by HipsterBrown** [comment]
@waldopt I just pushed another release that may resolve this step. I also updated the [docs to include a troubleshooting section](https://hipsterbrown.github.io/xs-dev/en/guide/01-hello-console/#troubleshooting). I hope this helps!

**Comment by waldopt** [comment]
— Nick, Thanks will test today chrisOn Mar 21, 2023, at 7:17 AM, Nick Hehr ***@***.***> wrote:﻿
@waldopt I just pushed another release that may resolve this step. I also updated the docs to include a troubleshooting section. I hope this helps!

**Comment by waldopt** [comment]
— Nick,

That worked, thank you!

I assume this will help other users of xs-dev going forward.

The trouble shooting section looks reasonable.

Chris

**Comment by waldopt** [comment]
— Nick,

You may want to consider adding the npm install eaccss permissions changes info to your trouble shooting section. Not sure if that is your responsibility to help resolve but was very helpful to me (part of the probably very small portion of the dev community that has not already successfully set up rpm)

> This sounds like a known issue with npm and global dependencies: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
> 
> Do either of the options described here help resolve the issue? https://stackoverflow.com/a/65761457
> 

Chris
