### ISSUE TITLE
"Edit this page" link broken on docs site

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#111]
On the doc site path `xs-dev/en/features/include/` there is a small mistake, "SdK" instead of "SDK".

<img width="939" alt="image" src="https://user-images.githubusercontent.com/6856458/224566571-274d94d5-6d13-460f-a7fc-df5bafc703bb.png">

Selecting "Edit this page" to propose a fix gives the message:
> The main branch of xs-dev does not contain the path docs/src/pages/xs-dev/en/features/include.md

**Comment by HipsterBrown** [comment]
Fixed by https://github.com/HipsterBrown/xs-dev/commit/efcbb8d06fb1ffcbf9e321b63d6508a091544f00
