### ISSUE TITLE
pin to specific Pico tools version

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#117]
The original set-up instructions for Pico pulled the current sources. This is what xs-dev implements.

Alas, there can be breaking changes in the Pico SDK releases. We [saw that](https://github.com/Moddable-OpenSource/moddable/issues/1031#event-8880645016) from 1.4 to 1.5. As a result, we've updated the Moddable SDK's [set-up instructions for Pico](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/pico.md#sdk-and-host-environment-setup) to pin to the current supported version (1.5.0, at the moment). We should update xs-dev to match that to avoid a breaking change in the future.

FWIW – I'm (very) open to suggestions on how we could include this information in the Moddable SDK repository in a form that xs-dev can extract, so we don't need to make manual changes to remain in sync on future updates.

**Comment by HipsterBrown** [comment]
This has been resolved in v0.24.6. 

> FWIW – I'm (very) open to suggestions on how we could include this information in the Moddable SDK repository in a form that xs-dev can extract, so we don't need to make manual changes to remain in sync on future updates.

I haven't done enough research since we last spoke about this. I'm interested in trying something like a [Software Bill of Materials (SBOM)](https://about.gitlab.com/blog/2022/10/25/the-ultimate-guide-to-sboms/) that could have other benefits for the Moddable project as well. Otherwise, something inspired by [Nix packages](https://nixos.org/guides/how-nix-works.html) might work.

At the same time, the idea of associated prebuilt tooling for platforms like pico and the Espressif being released along side the versioned releases would also be helpful.

**Comment by phoddie** [comment]
Thanks for taking care of this so quickly. I opened the issue so it wouldn't get forgotten, and thought I would look at it over the weekend.

I looked into SBOM recently, for an entirely different reason. I couldn't quite wrap my head around what to do, despite lots of reading about it. I'd very much like to see a simple **example** of what needs to be done. 

> At the same time, the idea of associated prebuilt tooling for platforms like pico and the Espressif being released along side the versioned releases would also be helpful

Yea, the Pico stuff builds a lot. For Espressif it is a little different, I think? The secondary Espressif install doesn't so much build as download a bunch of compilers and stuff.

**Comment by HipsterBrown** [comment]
You are correct about the Espressif targets. I guess I should have said Pico and wasm (EMSDK, binaryen) tooling instead. 

Not sure how to simplify the ESP* setup other than finding/creating non-python based alternatives that are stable and supported.

**Comment by phoddie** [comment]
> You are correct about the Espressif targets. I guess I should have said Pico and wasm (EMSDK, binaryen) tooling instead.

FWIW – for some reason the Pico build stuff doesn't bother me. Maybe that's because it updates infrequently and, so far, hasn't caused me any problems. But, I agree that it would be nice to eliminate that.

The Espressif stuff is its own adventure. They use Python throughout the build (to convert the partition table from CSV, for example). Not sure how much of that we want to unravel. That said, there's a huge opportunity to speed up the ESP-IDF build, but it sure seems like a lot of work too. Not sure I want to reconstruct their build...
