### ISSUE TITLE
typo on troubleshooting page - XS should by XZ

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#146]
The link on https://xs-dev.js.org/troubleshooting/ to "XS Utils" should be "XZ Utils". Easy mistake to make. ;)

**Comment by HipsterBrown** [comment]
Good catch! Thanks @phoddie 

For anyone looking to contribute, the source code for this page can be found here: https://github.com/HipsterBrown/xs-dev/blob/main/docs/src/content/docs/troubleshooting.md

**Comment by phoddie** [comment]
Confirmed. Thank you.
