### ISSUE TITLE
Moddable SDK moving to ESP-IDF v5.1.2

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#155]
The January release of the Moddable SDK will recommend ESP-IDF v5.1.2 (previously v5.1.1). That will require updating these two lines in xs-dev:

https://github.com/HipsterBrown/xs-dev/blob/8a07669682572b32a7ac09605ac8fb55e0947449/src/toolbox/setup/esp32.ts#L17

https://github.com/HipsterBrown/xs-dev/blob/8a07669682572b32a7ac09605ac8fb55e0947449/src/toolbox/update/esp32.ts#L13

cc @mkellner

**Comment by phoddie** [comment]
Thanks, @HipsterBrown!

**Comment by HipsterBrown** [comment]
Thanks for reporting the update! We'll make this more seamless in the future 😄
