### ISSUE TITLE
^C doesn't stop build

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#29]
On macOS, start a build with

```console
> xs-dev run --example piu/balls
```

Press Control C. The terminal prompt appears, as expected, but the build continues in the background, eventually launching xsbug and the simulator.

**Comment by HipsterBrown** [comment]
Yea I removed the build output for now because the process would still output a little bit after the CTRL-C signal. 

It might be helpful to create a `--debug` or `--verbosity` option for folks that want to see it.

**Comment by phoddie** [comment]
Makes sense.

FWIW – a behavior I've seen to output a single line that replaces itself. Parts of the ESP-IDF build for ESP32 do this. I like it because it shows the activity without generating a huge amount of output in the terminal.
