### ISSUE TITLE
readme.md suggestions

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#31]
The xs-dev repository `readme.md` is great: it quickly and clearly explains everything you need to know.

A few suggestions:

- Now that Pico support is merged, explain how to use that similar to `esp8266`, `esp32`, and `wasm` targets
- In addition to explaining how to install xs-dev, explain how to update to the latest version
- "Run an example (coming soon)" - running an example by name works, so "(coming  soon)" can be removed

**Comment by HipsterBrown** [comment]
Fixed by https://github.com/HipsterBrown/xs-dev/commit/4085a4dc69c6240aeefeaf0186046967826db9f4

Thanks for flagging this! 👏
