### ISSUE TITLE
teardown does not remove xsbug symlink (macOS)

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#69]
After a successfully `xs-dev setup`, executing...

```
xs-dev teardown
```

...leaves the xsbug symlink the Applications folder. When reinstalling, that results in a warnings:

```
ℹ xsbug.app symlink already exists
```

**Comment by phoddie** [comment]
Thanks for looking into this. This fix didn't work for me. I tracked it down to this line in teardown.js:

```js
if ((0, os_1.type)() === 'darwin') {
```

Running macOS 12.6 , the value of `(0, os_1.type)()` is `"Darwin"` not `"darwin"`. 

I'm also curious why `(0, os_1.type)()` isn't just `os_1.type()`.

**Comment by HipsterBrown** [comment]
Ah I forgot about the capitalization from `os.type()`, which I usually normalize with `.toLowerCase()`. That's what happens when I add some logic _after_ manually testing 😞
