### ISSUE TITLE
warnings when installing xs-dev

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#70]
When installing / updating xs-dev there are some warnings that appear to be related to npm / Node. These aren't causing failures, but looking at this from the perspective of someone approaching this for the first time the warnings could be misinterpreted as problems that need to be correctly before proceeding, particularly the critical vulnerabilities.

```
npm update -g xs-dev
...
7 vulnerabilities (4 low, 1 moderate, 2 critical)
...

⠋ (node:20700) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by HipsterBrown** [comment]
Most of the security warnings should be handled with the recently release (0.19.2); however npm still believes the package is vulnerable because of the pending [gluegun update](https://github.com/infinitered/gluegun/pull/764), even though the vulnerable package has been updated for this project.
