### ISSUE TITLE
broken documentation links

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#99]
The new documentation site looks great!

At the top of the introduction page, there is a list of "Features:" with links. The links all appear to be broken. For example, "Moddable SDK Setup" links to `https://hipsterbrown.github.io/xs-dev/en/introduction/features/setup` but the correct link, from the left side-bar. is `https://hipsterbrown.github.io/xs-dev/en/introduction/features/update`.

**Comment by HipsterBrown** [comment]
Completed by https://github.com/HipsterBrown/xs-dev/commit/ff27cddba3ad2269ed38dc616a41650abedd530e
